import { useNavigate } from 'react-router-dom'

import { LogoMark } from '../components/Logo.jsx'
import PageMotif from '../components/PageMotif.jsx'
import { ROLE_HOME } from '../roles.js'
import { CARD_OPTION, LABEL, MOTION } from '../ui.js'

// The front door. It is NOT authentication and does not pretend to be:
// declared limitation 4 says roles are a dropdown switcher, and this screen is
// that same switcher given a door to stand in. Nothing is verified, nothing is
// stored, and the page says so in body text rather than burying it.
//
// Register, deliberately: this reads like the landing page of an internal
// departmental tool — an emblem, the service name, the cycle it covers, and a
// list of views to continue into. No welcome, no reassurance, no floating card
// on an empty ground. The honesty line at the foot is written in the same dry
// voice as the memo's "Not generated by a language model" caption, because it
// is doing the same job.

// One line-icon per role, so the three cards are told apart by SHAPE and not by
// colour. Colour is not available for this job: coral, gold and green already
// mean High, Medium and Low everywhere else in the app, and spending them on
// three roles here would put a severity reading on a choice that has none.
//
// Drawn on the same 32-unit grid at the same 2.5-unit stroke as the logo mark,
// with the same flat, sharp-cornered, rectilinear vocabulary — no circles, no
// rounded caps. Each one deliberately has a different silhouette rather than a
// different detail, because at 24px silhouette is all that survives: banded
// horizontals for the list, a stepped diagonal for the route, a vertical spine
// for the trail. Each also rhymes with its page's background motif.
const ICONS = {
  // A ranked list: bulleted rows.
  Officer: (
    <>
      <rect x="5" y="6.75" width="4.5" height="4.5" fill="currentColor" />
      <rect x="5" y="13.75" width="4.5" height="4.5" fill="currentColor" />
      <rect x="5" y="20.75" width="4.5" height="4.5" fill="currentColor" />
      <path d="M14 9H27M14 16H27M14 23H27" stroke="currentColor" strokeWidth="2.5" />
    </>
  ),
  // A route stepping up to a waypoint.
  Inspector: (
    <>
      <path d="M5 25H14V13H22" stroke="currentColor" strokeWidth="2.5" strokeLinejoin="miter" />
      <rect x="20.5" y="9.5" width="7" height="7" fill="currentColor" />
    </>
  ),
  // A trail: a spine with ticks along it, one of them major.
  Auditor: (
    <>
      <path d="M8 4V28" stroke="currentColor" strokeWidth="2.5" />
      <path d="M8 9H18M8 16H25M8 23H18" stroke="currentColor" strokeWidth="2.5" />
    </>
  ),
}

function RoleIcon({ role }) {
  return (
    <svg
      width="24"
      height="24"
      viewBox="0 0 32 32"
      fill="none"
      // Navy at rest, white once the card inverts. The role name beside it says
      // the same thing in words, so the icon is decoration to a screen reader.
      className={`shrink-0 text-navy ${MOTION} group-hover:text-white group-focus-visible:text-white`}
      aria-hidden="true"
      focusable="false"
    >
      {ICONS[role]}
    </svg>
  )
}

// Each option says what that view actually shows. An officer who has never
// seen this build should be able to pick correctly from this list alone. Kept
// to one line apiece: three cards are a choice to scan, and a second wrapped
// line on each turns the group back into three heavy panels.
const VIEWS = [
  { role: 'Officer', detail: 'The ranked case list, and the trace behind each score.' },
  { role: 'Inspector', detail: 'The same cases in visit order. Record a field note.' },
  { role: 'Auditor', detail: 'The append-only trail. Re-derive a score from stored inputs.' },
]

export default function SignIn({ onSelect }) {
  const navigate = useNavigate()

  // Each role lands on its own screen, read from the same ROLE_HOME map the
  // top-bar switcher uses. Choosing Inspector here and choosing Inspector from
  // the switcher mid-session are the same action and go to the same place.
  function choose(role) {
    onSelect(role)
    navigate(ROLE_HOME[role])
  }

  return (
    <main className="relative isolate flex min-h-screen flex-col">
      <PageMotif variant="signin" />

      <div className="mx-auto flex w-full max-w-xl flex-1 flex-col justify-center px-8 py-12">
        <div className="flex flex-col items-center">
          <LogoMark size={64} className="text-navy" />
          <h1 className="mt-4 font-display text-page-title tracking-wide text-navy">LEAKPROOF</h1>
          {/* The same line the top bar carries, so the door and the room behind
              it are stamped with the same cycle. */}
          <p className="mt-2 text-meta-label uppercase text-ink-secondary">
            Public Distribution System · Uttar Pradesh · cycle 2026-08
          </p>
        </div>

        {/* A hairline, not a card edge: the header block and the role list are
            two parts of one sheet, not two floating panels. */}
        <div className="mt-8 border-t border-border pt-8">
          <p className={LABEL}>Continue as</p>

          <ul className="mt-2 space-y-2">
            {VIEWS.map((view) => (
              <li key={view.role}>
                {/* A bordered surface card at rest, inverting to navy on hover
                    and on keyboard focus. px-4 py-2 rather than the 16px ROW
                    padding: three cards are a selection group, and the extra
                    8px top and bottom on each was what made them read as three
                    panels instead. */}
                <button
                  type="button"
                  onClick={() => choose(view.role)}
                  className={`${CARD_OPTION} flex w-full items-center gap-4 px-4 py-2 text-left`}
                >
                  <RoleIcon role={view.role} />

                  <span className="min-w-0 flex-1">
                    <span
                      className={`block text-body font-medium text-ink ${MOTION} group-hover:text-white group-focus-visible:text-white`}
                    >
                      {view.role}
                    </span>
                    {/* ink-secondary on white reads 6.15:1 at rest; white/70 on
                        navy reads 7.81:1 once inverted — the same device the
                        sidebar already uses for secondary text on that ground,
                        rather than a new token invented for one screen. */}
                    <span
                      className={`block text-body-secondary text-ink-secondary ${MOTION} group-hover:text-white/70 group-focus-visible:text-white/70`}
                    >
                      {view.detail}
                    </span>
                  </span>

                  {/* The arrow slides 4px on hover — the same cue the buttons
                      got last pass, in the one direction this card goes. */}
                  <span
                    aria-hidden="true"
                    className={`shrink-0 text-body text-ink-secondary ${MOTION} group-hover:translate-x-1 group-hover:text-white/70 group-focus-visible:translate-x-1 group-focus-visible:text-white/70`}
                  >
                    →
                  </span>
                </button>
              </li>
            ))}
          </ul>

          {/* On the screen, at body-secondary size, not in a tooltip and not in
              the deck only. Same discipline as the memo caption on Case
              Detail: the limitation is stated where the thing is used. */}
          <p className="mt-4 text-body-secondary text-ink-secondary">
            No password required — this demo uses role selection, not authentication. See Declared
            Limitations.
          </p>
        </div>

        <p className="mt-8 border-t border-border pt-4 text-meta-label text-ink-secondary">
          Synthetic data, seed 4521 · demo build, not a system of record.
        </p>
      </div>
    </main>
  )
}
